### ISSUE TITLE
Error when opening xls file - IOError: incorrect end of DIFAT

### ISSUE THREAD

**Issue by prasanna-sk** [decalage2/olefile#117]
Not sure if this is a bug. I am not sure if this is a bug. I am trying to extract the data from excel workbook and it seems to open file in MS Office 365.

But, I do get an error when opening an xls file - 

`IOError: incorrect end of DIFAT`

I am not in a position to send the file as it has some confidential info. If there are other diagnostic commands I need to run, I can run them. 

It seems to be an old xls (97-2003) file with hidden sheet & a vb macro.

To Reproduce -  xls variable has the filename
```
>>> olefile.isOleFile(xls)
True
>>> ole = olefile.OleFileIO(xls)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/olefile/olefile.py", line 1075, in __init__
    self.open(filename, write_mode=write_mode)
  File "/usr/lib/python2.7/site-packages/olefile/olefile.py", line 1348, in open
    self.loadfat(header)
  File "/usr/lib/python2.7/site-packages/olefile/olefile.py", line 1562, in loadfat
    raise IOError('incorrect end of DIFAT')
IOError: incorrect end of DIFAT
```

**Version information:**
 - OS: Rhel Linux 
 - OS version: 7.2 - 64 bits
 - Python version: 2.7.5
 - olefile version: 0.46 (latest)

**Comment by decalage2** [comment]
OK, could you please run olefile.py from the command line, adding options `-c` and `-d` to get more debug information? Thanks.

**Comment by prasanna-sk** [comment]
Here you go. Thanks.
[olefile_debug.txt](https://github.com/decalage2/olefile/files/3104637/olefile_debug.txt)
[olefile_console_debug.txt](https://github.com/decalage2/olefile/files/3104638/olefile_console_debug.txt)
