### ISSUE TITLE
module 'olefile' has no attribute 'OleFileIO'

### ISSUE THREAD

**Issue by hildeb** [decalage2/olefile#152]
I'm using olevba from within olefy and I'm getting this error:

olefy ERROR oletools <308750> olevba returned <30 chars - rc: 1, response: '', error: '
Traceback (most recent call last):
  File "/usr/local/bin/olevba", line 5, in <module>
    from oletools.olevba import main
  File "/usr/local/lib/python3.10/dist-packages/oletools/olevba.py", line 342, in <module>
    from oletools import rtfobj
  File "/usr/local/lib/python3.10/dist-packages/oletools/rtfobj.py", line 133, in <module>
    from oletools import oleobj, ftguess
  File "/usr/local/lib/python3.10/dist-packages/oletools/oleobj.py", line 71, in <module>
    from oletools.ppt_record_parser import (is_ppt, PptFile,
  File "/usr/local/lib/python3.10/dist-packages/oletools/ppt_record_parser.py", line 57, in <module>
    from oletools import record_base
  File "/usr/local/lib/python3.10/dist-packages/oletools/record_base.py", line 84, in <module>
    OleFileIO = olefile.OleFileIO\nAttributeError: module \'olefile\' has no attribute \'OleFileIO\'

I wonder if this is an error in olevba

**Comment by decalage2** [comment]
Hi @hildeb, have you checked if olefile is properly installed, and which version it is? You can use `pip list`, and the olefile version should be 0.46.

**Comment by decalage2** [comment]
This is really strange, olevba does not trigger that error on my Linux with Python 3.10. I really wonder what would trigger this error if olefile is installed properly. 🤔
