### ISSUE TITLE
Windows 10, Python v3.6.3, olefile v0.44 UnicodeDecodeError

### ISSUE THREAD

**Issue by Ivan-Castro** [decalage2/olefile#80]
Trying to install olefile through` pip install Pillow`, I got: 

```
C:\Users\Iván>pip install Pillow
Requirement already satisfied: Pillow in c:\users\iván\appdata\local\programs\python\python36-32\lib\site-packages\pillow-4.3.0-py3.6-win32.egg
Collecting olefile (from Pillow)
  Using cached olefile-0.44.zip
Installing collected packages: olefile
  Running setup.py install for olefile ... error
Exception:
Traceback (most recent call last):
  File "c:\users\iván\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 57: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\iván\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\iván\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\iván\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\iván\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\iván\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\iván\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 57: invalid continuation byte
```

**Comment by hugovk** [comment]
Do you get the same with "pip install olefile"? 

You could first try "python -m pip install -U pip setuptools" just in case.

**Comment by decalage2** [comment]
When I read the error messages, it looks like an exception in pip due to the special character in the user name (C:\Users\Iván), and not an olefile issue. I'll close it, feel free to reopen if you have more evidence it's linked to olefile.
